// Code generated by "stringer -type=RunResult"; DO NOT EDIT.

package status

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FailedRun-0]
	_ = x[SuccessfulRun-1]
}

const _RunResult_name = "FailedRunSuccessfulRun"

var _RunResult_index = [...]uint8{0, 9, 22}

func (i RunResult) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RunResult_index)-1 {
		return "RunResult(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RunResult_name[_RunResult_index[idx]:_RunResult_index[idx+1]]
}
