// Code generated by "stringer -type=Direction"; DO NOT EDIT.

package direction

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[North-0]
	_ = x[East-1]
	_ = x[South-2]
	_ = x[West-3]
}

const _Direction_name = "NorthEastSouthWest"

var _Direction_index = [...]uint8{0, 5, 9, 14, 18}

func (i Direction) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Direction_index)-1 {
		return "Direction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Direction_name[_Direction_index[idx]:_Direction_index[idx+1]]
}
